### ISSUE TITLE
CREATE-SPECIAL-USE doesn't work

### ISSUE THREAD

**Issue by falon** [cyrusimap/cyrus-imapd#2592]
I follow RFC6154, p.5.3. If I create a folder with special use:

```
localhost> telnet 0 143
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=PLAIN AUTH=LOGIN SASL-IR] tst-msg02.csi.it Cyrus IMAP 3.0.8-2.el7 RHEL server ready
a01 login admin admin
a01 OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION URLAUTH URLAUTH=BINARY LOGINDISABLED XCONVERSATIONS COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE] User logged in SESSIONID=<cyrus-19645-1543505418-1-6473868810642192219>
a CAPABILITY
* CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION URLAUTH URLAUTH=BINARY LOGINDISABLED XCONVERSATIONS COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE
a OK Completed

a CREATE user/gino.tino/ziopino@example.com (USE (\Drafts))
a OK Completed
```
the server returns OK, but no specialuse flag is created:

```
localhost> info user/gino.tino/ziopino@example.com
{user/gino.tino/ziopino@example.com}:
  private:
    check: NIL
    checkperiod: NIL
    comment: NIL
    sort: NIL
    specialuse: NIL
    thread: NIL
    path: NIL
    expire: NIL
    news2mail: NIL
    sieve: NIL
    squat: NIL
  shared:
    check: NIL
    checkperiod: NIL
    comment: NIL
    sort: NIL
    specialuse: NIL
    thread: NIL
    path: NIL
    annotsize: 7
    duplicatedeliver: false
    expire: NIL
    lastpop: NIL
    lastupdate: 29-Nov-2018 16:32:02 +0100
    news2mail: NIL
    partition: maildata4
    pop3newuidl: true
    pop3showafter: NIL
    sharedseen: false
    sieve: NIL
    size: 0
    squat: NIL
    synccrcs: 0 0
    uniqueid: wukf292v0julkk6d2u22438r
```
cyradm cm command works bad in the same way.
